apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
            # 1) 스크랩 여부
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            regex: "true"
            action: keep
    
          # 2) IP:PORT 조합하여 __address__ 설정
          - source_labels:
              - __meta_kubernetes_pod_ip
              - __meta_kubernetes_pod_annotation_prometheus_io_port
            regex: "(.+);(.+)"
            replacement: "$1:$2"
            target_label: __address__
    
          # 3) 경로 설정
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            regex: (.+)
            replacement: $1
            target_label: __metrics_path__