apiVersion: v1
kind: Service
metadata:
  name: prometheus-dev-svc
  namespace: monitoring
spec:
  selector:
    app: prometheus-dev
  ports:
    - name: web
      port: 9090
      targetPort: 9090
    - name: otlp-grpc
      port: 4317
      targetPort: 9090
      protocol: TCP
  type: ClusterIP