apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      max_chunk_age: 1h
      chunk_target_size: 1048576
      wal:
        enabled: true
        dir: /loki/wal

    schema_config:
      configs:
        - from: 2023-01-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    storage_config:
      tsdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/tsdb-cache
      filesystem:
        directory: /loki/chunks

    compactor:
      working_directory: /loki/compactor
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: filesystem
    
    table_manager:
      retention_deletes_enabled: true
      retention_period: 180d
    
    tracing:
      enabled: true

    limits_config:
      allow_structured_metadata: true
      otlp_config:
        resource_attributes:
          attributes_config:
            - action: index_label
              attributes:
                - service.name
                - service.namespace
                - environment
                - pod
                - container

    distributor:
      otlp_config:
        default_resource_attributes_as_index_labels:
          - service.name
          - service.namespace
          - deployment.environment
          - k8s.namespace.name
          - k8s.pod.name
          - k8s.container.name
