apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-dev
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki-dev
  template:
    metadata:
      labels:
        app: loki-dev
    spec:
      nodeSelector:
        node-pool: monitoring
      containers:
        - name: loki-dev
          image: grafana/loki:3.0.0
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: 3100
              name: http
            - containerPort: 9095
              name: grpc
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-data
              mountPath: /loki
          resources:
            requests:
              cpu: 300m
              memory: 400Mi
            limits:
              cpu: 600m
              memory: 800Mi
      securityContext:
        fsGroup: 10001
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-data
          persistentVolumeClaim:
            claimName: loki-pvc