apiVersion: v1
kind: Service
metadata:
  name: loki-dev-svc
  namespace: monitoring
spec:
  selector:
    app: loki-dev
  ports:
    - port: 3100
      targetPort: 3100
      name: http
    - port: 9095
      targetPort: 9095
      name: grpc
  type: ClusterIP