apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetwo-config-service-dev
  labels:
    app: onetwo-config-service-dev
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: onetwo-config-service-dev
  template:
    metadata:
      labels:
        app: onetwo-config-service-dev
    spec:
      imagePullSecrets:
        - name: onetwo-docker-secret
      nodeSelector:
        node-pool: default

      securityContext:
        runAsUser: 2000
        runAsNonRoot: true
        fsGroup: 2000

      initContainers:
        - name: otel-agent-downloader
          image: curlimages/curl:8.7.1
          command:
            - sh
            - -c
            - curl -sSL -o /otel/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.14.0/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel

      containers:
        - name: onetwo-config-service-dev
          image: 549834666340.dkr.ecr.ap-northeast-2.amazonaws.com/onetwo2.0/config-service:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{ "server.port": 9999 }'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4317
            - name: OTEL_SERVICE_NAME
              value: config-service
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=dev
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+TieredCompilation \
                  -XX:TieredStopAtLevel=1 \
                  -XX:MinRAMPercentage=50.0 \
                  -XX:MaxRAMPercentage=80.0 \
                  -XX:+AlwaysPreTouch \
                  -javaagent:/otel/opentelemetry-javaagent.jar \
                  -Dotel.javaagent.enabled=true \
                  -Dotel.metrics.exporter=otlp \
                  -Dotel.traces.exporter=otlp \
                  -Dotel.logs.exporter=otlp \
                  -Dotel.exporter.otlp.endpoint=http://localhost:4317 \
                  -Dotel.exporter.otlp.protocol=grpc \
                  -Dotel.instrumentation.logging.auto-attributes.enabled=true"
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          livenessProbe:
            tcpSocket:
              port: 9999
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: 9999
            periodSeconds: 20
            failureThreshold: 5
            timeoutSeconds: 1
          startupProbe:
            tcpSocket:
              port: 9999
            periodSeconds: 120
            failureThreshold: 5
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 400m
              memory: 500Mi
          securityContext:
            runAsUser: 2000
            runAsNonRoot: true

        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.98.0
          args:
            - "--config=/etc/otel/config.yaml"
          ports:
            - containerPort: 4317
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel

      volumes:
        - name: otel-agent
          emptyDir: { }
        - name: otel-config
          configMap:
            name: otel-collector-config
---
