apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  config.yaml: |-
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095
    
    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: "0.0.0.0:4317"
            http:
              endpoint: "0.0.0.0:4318"
    
    ingester:
      lifecycler:
        ring:
          replication_factor: 3
      max_block_bytes: 104857600
      max_block_duration: 10m
      complete_block_timeout: 15m
    
    storage:
      trace:
        backend: local
        local:
          path: /tempo-data/blocks
        wal:
          path: /tempo-data/wal
    
    metrics_generator:
      registry:
        external_labels:
          source: tempo
          cluster: kubernetes-cluster
      storage:
        path: /tempo-data/generator/wal
        remote_write:
          - url: http://prometheus-dev-svc:9090/api/v1/write
            send_exemplars: true
    
    compactor:
      compaction:
        block_retention: 48h
