apiVersion: v1
kind: Service
metadata:
  name: tempo-dev-svc
  namespace: monitoring
spec:
  selector:
    app: tempo-dev
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: grpc
      port: 4317
      targetPort: 4317
  type: ClusterIP